Theme GTK3/4 window controls to match COSMIC theme
pop-os/libcosmic pull request #464
Opened 2024-05-25 17:09 UTC by nabrious0

#### This PR relies on the COSMIC GTK3/4 theming feature and extends it to also theme window control buttons 
_(This covers colors, hover background color, window active/inactive state colors, transitions (animations) and more...)_ 

**Examples below ( ↓ )**

**Eddy - GTK3 (Light/Dark)**
![image](https://github.com/pop-os/libcosmic/assets/162843960/ac9414a5-13f0-4996-9da7-03e0c7f68412)
![image](https://github.com/pop-os/libcosmic/assets/162843960/877d3814-ee8e-4bb7-9144-c73d4faa6cc8)

**Flatseal - GTK4|libadwaita (Light/Dark)**
![image](https://github.com/pop-os/libcosmic/assets/162843960/6db84685-1c04-49ba-be0a-95481d3c5fdd)
![image](https://github.com/pop-os/libcosmic/assets/162843960/b0105443-b3a6-4c08-8b3d-5d4360c28101)

**Main Menu - GTK4|libadwaita (Light/Dark)**
![image](https://github.com/pop-os/libcosmic/assets/162843960/3fb88f3e-5dfa-4211-8f8c-c619182965ea)
![image](https://github.com/pop-os/libcosmic/assets/162843960/4db2fdf1-a79f-47e6-9ea8-156aa4f2650f)

**Nautilus (GNOME Files) - GTK3 (Light/Dark)**
![image](https://github.com/pop-os/libcosmic/assets/162843960/b7a78b5d-d436-4fb1-9db2-3f3678dcb7f9)
![image](https://github.com/pop-os/libcosmic/assets/162843960/9192f8b2-32d7-4b3c-83bb-0fc22d6aaa3a)

2024-05-25 18:44 UTC, mmstick commented
Is it possible to make all icons in the header bar match the accent color?

2024-05-25 19:10 UTC, nabrious0 commented
> Is it possible to make all icons in the header bar match the accent color?

Haven't looked into it but I'm 99.99% sure it's possible, I'll check and report back.

2024-05-25 19:34 UTC, nabrious0 commented
> Is it possible to make all icons in the header bar match the accent color?

![image](https://github.com/pop-os/libcosmic/assets/162843960/fa5b6b13-e5f3-40af-bec9-1e7bedcaec34)

Yup, it is.

2024-05-25 19:45 UTC, nabrious0 commented
**Here are updated screenshots to include the colored icons:**

**Main Menu - GTK4|libadwaita**
![image](https://github.com/pop-os/libcosmic/assets/162843960/08ef46b1-8443-4dfe-8f75-b8f2b6f89530)
![image](https://github.com/pop-os/libcosmic/assets/162843960/8dff598c-665f-44e8-b752-f4199b13465e)

**Flatseal - GTK4|libadwaita**
![image](https://github.com/pop-os/libcosmic/assets/162843960/2884d755-8bd9-4991-829d-7da8611813f9)
![image](https://github.com/pop-os/libcosmic/assets/162843960/461da347-9b0d-4538-ab16-4a9c98550ecb)

**Nautilus (GNOME Files) - GTK3**
![image](https://github.com/pop-os/libcosmic/assets/162843960/39c599c3-4756-4800-93c4-b93bd4d32264)
![image](https://github.com/pop-os/libcosmic/assets/162843960/1eeffd32-1366-42ab-8350-8cb9294c9ef1)

2024-05-25 21:55 UTC, mmstick commented
I see that some icons still aren't being colored correctly, but that's closer to our designs than before. All icons should have the accent color whenever a window is focused, and then an inactive grey color when the window is unfocused. I'm not sure if it's possible to change the color based on window focus status in GTK.

2024-05-25 22:53 UTC, nabrious0 commented
> I see that some icons still aren't being colored correctly, but that's closer to our designs than before. All icons in the header bar should have the accent color whenever a window is focused, and then an inactive grey color when the window is unfocused. I'm not sure if it's possible to change the color based on window focus status in GTK.

It is possible, on libadwaita that is `.selector**:backdrop** {}` and I already do that for libadwaita on GTK3 I have yet to find the selector.

2024-05-27 23:09 UTC, nabrious0 commented
Colors even more icons according to accent color, and makes them all gray when a window is inactive (currently exclusive to libadwaita)

![image](https://github.com/pop-os/libcosmic/assets/162843960/75cbde1a-696f-4aeb-8213-6497f1a0ebb6)
![image](https://github.com/pop-os/libcosmic/assets/162843960/5e879e3c-b658-4373-92a6-a327d0877b7a)

2024-05-27 23:22 UTC, git-f0x commented
Just a note: afaik COSMIC apps use either 8px (Round, Slightly Round) or 2px (Square) window corner radius, at least from looking at the config in Settings.

2024-05-27 23:33 UTC, nabrious0 commented
> Just a note: afaik COSMIC apps use either 8px (Round, Slightly Round) or 2px (Square) window corner radius, at least from looking at the config in Settings.

Huh interesting, cause after setting it to 6px and putting a COSMIC app and libadwaita app on top of each other, they seemed to perfectly match, I'll double check.

2024-05-28 13:40 UTC, wash2 requested changes
This looks great! I've just suggested a couple small changes.

2024-05-28 13:40 UTC, wash2 commented on cosmic-theme/src/output/gtk4_output.rs
> +
```suggestion
        let corner_radius = self.corner_radii.radius_s[0];
```

2024-05-28 13:40 UTC, wash2 commented on cosmic-theme/src/output/gtk4_output.rs
> +	border-radius: 6px;
```suggestion
	border-radius: {corner_radius:.0}px;
```

2024-05-28 13:44 UTC, wash2 approved these changes
I applied the suggestions.

2024-05-28 13:46 UTC, nabrious0 commented
Awesome! I didn't even know getting the real border radii was possible, thanks!

2024-05-28 13:49 UTC, merged

2025-01-22 14:58 UTC, jackpot51 commented
No, we cannot reinstate this.