WIP: Interface density
pop-os/libcosmic pull request #603
Opened 2024-09-10 13:38 UTC by git-f0x

Since libcosmic seems to already have a Density enum, I moved most of the things from Settings here.
Values for non-default densities are placeholders until there are designs.
Not sure why the header height and padding don't change when changing the density ([code](https://github.com/pop-os/libcosmic/blob/b66f8986d1b897e53471f05fdc27b851cb4fa958/src/widget/header_bar.rs#L280)).
Should be tested alongside pop-os/cosmic-settings#577.

2024-09-14 01:19 UTC, git-f0x commented
I'm marking this ready for review, since it doesn't cause any visual changes, and I'm not sure if I'll be able to rebase this if the Iced rebase happens in the meantime.
Not sure why the header bars don't respond to density changes, so it would be nice to fix that before this is merged, if possible (but I haven't yet been able to find the cause).

2024-09-17 20:19 UTC, git-f0x commented
The biggest visual issue (that Compact makes stand out more), is that [this](https://github.com/pop-os/libcosmic/blob/f12de010ec2bd76ee46ef2a33642cf22e55ae87e/src/widget/list/column.rs#L43) needs to have a `min_height` of 32 (potentially less for Compact) to match designs, but I'm not sure how to implement that (as mentioned [here](https://github.com/pop-os/libcosmic/pull/598#issuecomment-2329428222)).

2024-09-17 23:18 UTC, git-f0x commented
Changing the `interface_density` config file doesn't seem to do anything. Should ThemeBuilder be changed to take interface density into account (possibly instead of spacing, or to set the spacing to the value of interface density)?

2024-09-18 03:37 UTC, wash2 commented
> Changing the `interface_density` config file doesn't seem to do anything. Should ThemeBuilder be changed to take interface density into account (possibly instead of spacing, or to set the spacing to the value of interface density)?

Ya the builder could have a method that sets spacing based on the provided density value. And the settings app could set the value.

2024-09-18 08:29 UTC, git-f0x commented
How would the builder access the `interface_density` config file (so that it works without Settings)? I tried importing CosmicTk to `/cosmic-theme/src/model/theme.rs` but I only managed to get circular dependencies or "not found".

2024-09-18 15:36 UTC, git-f0x commented
Settings already sets the spacing of the theme builder to the chosen density, but the config file isn't used for anything (though I made it write the density to the file).
So should I just move Density to cosmic-theme, and leave everything else as is?
Also regarding [this](https://github.com/pop-os/libcosmic/blob/914d989049ea1a8c47f0690cdbbfe3f862cc491d/src/app/mod.rs#L684), how would I access the current density, so that the padding and spacing could match the header bar (e.g. `padding = if Compact { 2 } else { 8 }`)?

2024-09-18 18:18 UTC, git-f0x commented
The NavBar side looks slightly bad with only 2 as padding, but not sure if the header bar horizontal padding should be increased (so that this can be increased as well).
![screenshot-2024-09-18-18-05-48](https://github.com/user-attachments/assets/a7ca729a-f34e-48e3-ad17-4a406dc6fa93)

Removing the conflicts caused by recent commits in Settings will take a bit of time.

2024-09-19 00:58 UTC, wash2 requested changes

2024-09-19 00:58 UTC, wash2 commented on cosmic-theme/src/model/density.rs
> +        if (value.space_m - 16) < 1 {
```suggestion
        if value.space_m.saturating_sub(16) == 0 {
```

2024-09-19 00:58 UTC, wash2 commented on cosmic-theme/src/model/density.rs
> +        } else if (value.space_m - 24) < 1 {
```suggestion
        } else if value.space_m.saturating_sub(24) == 0 {
```

2024-09-19 00:58 UTC, wash2 commented on src/widget/header_bar.rs
> +                        .padding(8)
Does this padding not depend on density?

2024-09-19 00:58 UTC, wash2 commented on src/widget/header_bar.rs
> +                    .padding(8)
Does this padding not depend on density?

2024-09-19 06:36 UTC, git-f0x commented on src/widget/header_bar.rs
> +                        .padding(8)
It does, but the default padding from the widget makes the buttons in the header too small when Compact, and cut off when Spacious.
They still perfectly fit inside the header when Compact, and I think match the buttons in server side decorations, which seem to have the same header height as Compact.

2024-09-19 15:36 UTC, wash2 commented
> Should `interface_density` be removed from CosmicTk, since it isn't used anywhere, and the config file maybe moved to the builder (possibly also `header_size`)? Not sure what the `interface_density` config file can be used for, since it shouldn't be used by the builder to automatically set spacing so as to not override custom spacing values set by users, and the spacing can be set without it in Settings (`self.theme_builder.spacing = self.density.into()`).

I'm not sure what you mean. https://pop-os.github.io/libcosmic/cosmic/config/fn.interface_density.html returns the CosmicTk interface density value, and is used in your changes. And https://pop-os.github.io/libcosmic/cosmic/config/fn.header_size.html is used too.

2024-09-19 15:55 UTC, git-f0x commented
Oh, right, the config file is used in one place. Sorry for the needless question.
Those functions could maybe be moved to the builder (or elsewhere in cosmic-theme), since density is also in cosmic-theme. But probably not necessary.

2024-09-20 22:51 UTC, git-f0x commented
Sorry for bothering you, but could this potentially be merged soon, so that apps can update their libcosmic version for easier testing of what needs tweaks (and so that the Settings PR doesn't pull from my fork)?
The one thing I'm not entirely sure about is the way of getting the spacing values. I've seen something like this used in some places:
```
let guard = crate::theme::THEME.lock().unwrap();
let theme = guard.cosmic();
```
and in others something like `theme::active()::cosmic()`. Not sure what it optimal.

2024-09-20 22:59 UTC, mmstick commented
We do need some functions to make `cosmic::theme::active().cosmic().spacing` more ergonomic.

2024-09-21 03:50 UTC, wash2 submitted a review, later dismissed

2024-09-21 16:46 UTC, git-f0x commented
Oh, I didn't know that adding a commit automatically dismisses a review. This just fixed the icons in text input becoming cut off or way to small with density changes.

2024-09-23 14:44 UTC, wash2 approved these changes

2024-09-23 14:46 UTC, wash2 commented
Could you fix the conflicts?

2024-09-23 14:48 UTC, git-f0x commented
It says on my end that it has no conflicts. So not sure what to do.

2024-09-23 16:08 UTC, wash2 approved these changes

2024-09-23 16:40 UTC, merged